CREATE TABLE MEMBRE(
	ID BIGINT NOT NULL AUTO_INCREMENT,
	PSEUDO VARCHAR(50) NOT NULL UNIQUE,
	EMAIL VARCHAR(64) NOT NULL UNIQUE,
	MDP CHAR(64) NOT NULL,
	PRIMARY KEY(ID)
);

CREATE TABLE GAME(
	ID VARCHAR(36) NOT NULL UNIQUE,
	STATUT VARCHAR(50),
	DIFFICULTE SMALLINT
);

CREATE TABLE PERSONNAGE(
	ID_MEMBRE BIGINT NOT NULL,
	NOM VARCHAR(50),
	XP INT
);